name: Build and deploy to Azure  

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Github Actions
        uses: actions/checkout@v2  

      - name: Log in to Azure via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myacregname.azurecr.io
          username: ${{ secrets.AZ_REGISTRY_USERNAME }}
          password: ${{ secrets.AZ_REGISTRY_PASSWORD }}
       

      - name: Build and push container image to Azure Container Registry
        run: |
          docker build -f backend/Dockerfile . -t myacregname.azurecr.io/api:${{ github.sha }}
          docker push myacregname.azurecr.io/api:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'okapi-ai'  # app name
          images: 'myacregname.azurecr.io/api:${{ github.sha }}'  # image name

      - name: Azure Logout
        run: |
          az logout
